### ISSUE TITLE
Deprecate in favour of purescript-pathy?

### ISSUE THREAD

**Issue by hdgarrood** [purescript-node/purescript-node-path#2]
What do people think?

**Comment by garyb** [comment]
:+1:

**Comment by cstrahan** [comment]
Given that `resolve` is impure and depends on `$PWD` ([see the PR I opened](https://github.com/purescript-node/purescript-node-path/pull/4)), I don't think this should be deprecated (although you might strip this package of all functions aside from `resolve`, and nest `resolve` under `purescript-pathy`'s module. I don't really care either way.).

**Comment by hdgarrood** [comment]
On second thoughts, I think this library is still useful, e.g. if you were just porting a node.js script to purescript and you just want the `path` module but in purescript.
