### ISSUE TITLE
Is `resolve` really effectful?

### ISSUE THREAD

**Issue by paluh** [purescript-node/purescript-node-path#20]
As usual thanks for providing all these bindings!

I'm able to `resolve` paths which don't exist on my machines so I'm not sure if `resolve` should be treated as effectful function. Am i missing something?

**Comment by hdgarrood** [comment]
It is, because it can give you access to the current working directory:

> If, after processing all given path segments, an absolute path has not yet been generated, the current working directory is used.

https://nodejs.org/api/path.html#path_path_resolve_paths
